version: '3.8'

services:
  ui: 
    image: 611184995116.dkr.ecr.ap-southeast-2.amazonaws.com/minglass-ui
    container_name: minglass-ui
    ports:
      - target: 80
        x-aws-protocol: http
    depends_on:
      - api

  api:
    image: 611184995116.dkr.ecr.ap-southeast-2.amazonaws.com/minglass-api
    x-aws-protocol: http
    container_name: minglass-api
    deploy:
          resources:
            limits:
              cpu: '0.5'
              memory: 512Mb
    ports:
      - target: 5000