version: '3.8'

services:
  postgres:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    container_name: postgres_local
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pg-data-local:/var/lib/postgresql/data

volumes:
  pg-data-local:
